# Generated by Django 5.2.1 on 2025-06-01 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='marca',
            field=models.CharField(choices=[('CHEVROLET', 'Chevrolet'), ('FIAT', 'Fiat'), ('FORD', 'Ford'), ('VOLKSWAGEN', 'Volkswagen'), ('RENAULT', 'Renault'), ('HONDA', 'Honda'), ('TOYOTA', 'Toyota'), ('HYUNDAI', 'Hyundai'), ('NISSAN', 'Nissan'), ('PEUGEOT', 'Peugeot'), ('CITROEN', 'Citroën'), ('JEEP', 'Jeep'), ('MITSUBISHI', 'Mitsubishi'), ('KIA', 'Kia')], max_length=100),
        ),
    ]
